export type Employee = {
  id: string
  name: string // text
  bio: string // longText
  age: number // number
  salary: number // currency
  completion: number // percent (fraction of 1)
  focusTime: number // duration (seconds)
  website: string // url
  email: string // email
  phone: string // phone
  department: string // singleSelect
  skills: string[] // multiSelect
  active: boolean // checkbox
  rating: number // rating (0..5)
  startDate: string // date (ISO)
}

export const employees: Employee[] = [
  {
    id: "1",
    name: "Clinton Mertz",
    bio: "Transferred from the Denver office; leads the payments squad.",
    age: 26,
    salary: 75814,
    completion: 0.82,
    focusTime: 5400,
    website: "https://clinton.example.com",
    email: "clinton_mertz@example.com",
    phone: "+14155552671",
    department: "sales",
    skills: ["ts", "react"],
    active: true,
    rating: 4,
    startDate: "2023-04-12",
  },
  {
    id: "2",
    name: "Kristie Tremblay",
    bio: "This employee has consistently exceeded targets for three quarters.",
    age: 31,
    salary: 107044,
    completion: 0.5,
    focusTime: 9000,
    website: "https://kristie.example.org",
    email: "kristie.tremblay@example.com",
    phone: "+442071838750",
    department: "eng",
    skills: ["ts", "sql", "lead"],
    active: true,
    rating: 5,
    startDate: "2021-09-01",
  },
  {
    id: "3",
    name: "Kevon Towne",
    bio: "Leading the diversity and inclusion council this year.",
    age: 44,
    salary: 80418,
    completion: 0.13,
    focusTime: 1500,
    website: "https://weary-lounge.example.com",
    email: "kevon.towne79@example.com",
    phone: "+33142685300",
    department: "sales",
    skills: ["design"],
    active: false,
    rating: 3,
    startDate: "2019-01-23",
  },
  {
    id: "4",
    name: "Bailey Shanahan",
    bio: "Excellent team player with deep platform knowledge.",
    age: 44,
    salary: 145563,
    completion: 1,
    focusTime: 12600,
    website: "https://faint-tenement.example.info",
    email: "bailey_shanahan@example.com",
    phone: "+493012345678",
    department: "hr",
    skills: ["lead", "design"],
    active: true,
    rating: 5,
    startDate: "2018-07-30",
  },
  {
    id: "5",
    name: "Beulah Bartell",
    bio: "Outstanding performance on the Q3 migration.",
    age: 61,
    salary: 104370,
    completion: 0.67,
    focusTime: 300,
    website: "https://cuddly-concentration.example.org",
    email: "beulah.bartell@example.com",
    phone: "+34911234567",
    department: "sales",
    skills: ["sql"],
    active: true,
    rating: 2,
    startDate: "2015-11-05",
  },
  {
    id: "6",
    name: "Velva Kshlerin",
    bio: "Outstanding performance; mentors two junior engineers.",
    age: 38,
    salary: 148812,
    completion: 0.9,
    focusTime: 7200,
    website: "https://impolite-seal.example.org",
    email: "velva_kshlerin@example.com",
    phone: "+390612341234",
    department: "fin",
    skills: ["ts", "react", "sql"],
    active: true,
    rating: 4,
    startDate: "2020-02-17",
  },
  {
    id: "7",
    name: "Olivia Koss",
    bio: "Participating in the leadership rotation program.",
    age: 56,
    salary: 133164,
    completion: 0.34,
    focusTime: 45,
    website: "https://fatal-import.example.com",
    email: "olivia.koss@example.com",
    phone: "+31612345678",
    department: "mktg",
    skills: [],
    active: false,
    rating: 3,
    startDate: "2017-06-19",
  },
  {
    id: "8",
    name: "Genesis Maggio",
    bio: "Transferred from the Lisbon office; owns the billing rewrite.",
    age: 38,
    salary: 113455,
    completion: 0.75,
    focusTime: 3660,
    website: "https://familiar-cauliflower.example.com",
    email: "genesis.maggio24@example.com",
    phone: "+16045550123",
    department: "hr",
    skills: ["react", "design", "lead"],
    active: true,
    rating: 5,
    startDate: "2022-10-11",
  },
]
