export type Task = {
  id: string
  title: string // text
  assignee: string // text
  // `string` (not a union) because `defineColumns`'s `col.singleSelect` key
  // constraint (`KeysMatching`) requires an exact `string` type match.
  priority: string // singleSelect: "low" | "medium" | "high" | "urgent"
  status: string // singleSelect: "todo" | "in_progress" | "review" | "done"
  hoursLogged: number // number
  budget: number // currency
  completed: boolean // checkbox
  dueDate: string // date (ISO)
}

export const tasks: Task[] = [
  {
    id: "1",
    title: "Set up CI pipeline",
    assignee: "Priya Shah",
    priority: "high",
    status: "done",
    hoursLogged: 12,
    budget: 2400,
    completed: true,
    dueDate: "2026-05-02",
  },
  {
    id: "2",
    title: "Design onboarding flow",
    assignee: "Marcus Lee",
    priority: "medium",
    status: "in_progress",
    hoursLogged: 8,
    budget: 3200,
    completed: false,
    dueDate: "2026-06-14",
  },
  {
    id: "3",
    title: "Migrate auth to OAuth2",
    assignee: "Ines Rossi",
    priority: "urgent",
    status: "in_progress",
    hoursLogged: 21,
    budget: 5600,
    completed: false,
    dueDate: "2026-07-18",
  },
  {
    id: "4",
    title: "Write API docs",
    assignee: "Priya Shah",
    priority: "low",
    status: "todo",
    hoursLogged: 0,
    budget: 900,
    completed: false,
    dueDate: "2026-08-01",
  },
  {
    id: "5",
    title: "Fix pagination bug",
    assignee: "Tomás García",
    priority: "high",
    status: "review",
    hoursLogged: 4,
    budget: 600,
    completed: false,
    dueDate: "2026-07-15",
  },
  {
    id: "6",
    title: "Upgrade Next.js to 16",
    assignee: "Marcus Lee",
    priority: "medium",
    status: "done",
    hoursLogged: 16,
    budget: 1800,
    completed: true,
    dueDate: "2026-04-28",
  },
  {
    id: "7",
    title: "Add dark mode support",
    assignee: "Ines Rossi",
    priority: "low",
    status: "todo",
    hoursLogged: 0,
    budget: 1200,
    completed: false,
    dueDate: "2026-08-20",
  },
  {
    id: "8",
    title: "Optimize bundle size",
    assignee: "Tomás García",
    priority: "medium",
    status: "in_progress",
    hoursLogged: 9,
    budget: 2000,
    completed: false,
    dueDate: "2026-07-30",
  },
  {
    id: "9",
    title: "Set up error tracking",
    assignee: "Priya Shah",
    priority: "high",
    status: "done",
    hoursLogged: 6,
    budget: 800,
    completed: true,
    dueDate: "2026-05-10",
  },
  {
    id: "10",
    title: "Redesign pricing page",
    assignee: "Marcus Lee",
    priority: "urgent",
    status: "review",
    hoursLogged: 27,
    budget: 4500,
    completed: false,
    dueDate: "2026-07-22",
  },
  {
    id: "11",
    title: "Audit accessibility",
    assignee: "Ines Rossi",
    priority: "medium",
    status: "todo",
    hoursLogged: 0,
    budget: 1500,
    completed: false,
    dueDate: "2026-09-05",
  },
  {
    id: "12",
    title: "Refactor grouped table",
    assignee: "Tomás García",
    priority: "high",
    status: "in_progress",
    hoursLogged: 14,
    budget: 3100,
    completed: false,
    dueDate: "2026-07-25",
  },
  {
    id: "13",
    title: "Write E2E test suite",
    assignee: "Priya Shah",
    priority: "medium",
    status: "review",
    hoursLogged: 18,
    budget: 2700,
    completed: false,
    dueDate: "2026-07-19",
  },
  {
    id: "14",
    title: "Localize date/currency fields",
    assignee: "Marcus Lee",
    priority: "low",
    status: "done",
    hoursLogged: 5,
    budget: 700,
    completed: true,
    dueDate: "2026-03-30",
  },
  {
    id: "15",
    title: "Plan Q3 roadmap",
    assignee: "Ines Rossi",
    priority: "urgent",
    status: "todo",
    hoursLogged: 3,
    budget: 0,
    completed: false,
    dueDate: "2026-07-12",
  },
  {
    id: "16",
    title: "Clean up unused dependencies",
    assignee: "Tomás García",
    priority: "low",
    status: "done",
    hoursLogged: 2,
    budget: 300,
    completed: true,
    dueDate: "2026-04-08",
  },
]
